app/models.py
from . import db, login_manager
from flask_login import current_user, UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime

class User(UserMixin, db.Model):
  __tablename__ = 'users'

  id = db.Column(db.Integer, primary_key=True)
  fname = db.Column(db.String(128))
  sname = db.Column(db.String(128))
  username = db.Column(db.String(255))
  email = db.Column(db.String(128))
  profile_pic = db.Column(db.String())
  dataJoined = db.Column(db.DateTime, default=datetime.utcnow())
  pass_secure = db.Column(db.String(255))

  comments = db.relationship('Comment', backref='users', lazy= 'dynamic')
  blog = db.relationship('Blog', backref='users', lazy= 'dynamic')



  @property
  def password(self):
    raise AttributeError("You Can't Read the password attribute")

  @password.setter
  def password(self, password):
    self.pass_secure = generate_password_hash(password)

  def verify_password(self, password):
    return check_password_hash(self.pass_secure, password)

  def __repr__(self):
    return f'{self.fname} {self.sname}'


class Blog(db.Model):
  __tablename__ = 'blog'
  
  id = db.Column(db.Integer, primary_key=True)
  title = db.Column(db.String(255))
  content = db.Column(db.String())
  dateposted = db.Column(db.DateTime, default=datetime.utcnow())
  user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

  comments = db.relationship('Comment', backref='blog', lazy='dynamic')

  def save_blog(self):
    db.session.add(self)
    db.session.commit()
  
  @classmethod
  def get_blogs_content(cls):
    return cls.query.all()

class Comment(db.Model):
  __tablename__ = 'comments'

  id = db.Column(db.Integer, primary_key = True)
  comment = db.Column(db.String(2000))
  user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
  blog_id = db.Column(db.Integer, db.ForeignKey('blog.id'))

  def save_comment(self):
    db.session.add(self)
    db.session.commit()

  @classmethod
  def delete_comment(cls, id):
    todele = cls.query.filter_by(id=id).first()
    db.session.delete(todele)
    db.session.commit()
  
  @classmethod
  def get_specific_comment(cls, id):
    return cls.query.filter_by(pitch_id = id).all()

@login_manager.user_loader
def load_user(user_id):
  return User.query.get(int(user_id))

class Quote:
  def __init__(self, author, quote):
    self.author = author
    self.quote = quote

class Subscribe(db.Model):
  __tablename__ = 'subscribers'

  id = db.Column(db.Integer, primary_key=True)
  email = db.Column(db.String())

  def save_subscriber(self):
    db.session.add(self)
    db.session.commit()

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, StringField, SubmitField
from wtforms.validators import Required

class BlogPostForm(FlaskForm):
  title = StringField('Blog Title', validators=[Required()])
  content =  TextAreaField('Blog Content',validators=[Required()], render_kw={'class': 'form-control', 'rows': 15})
  submit = SubmitField('Submit Post')

class CommentForm(FlaskForm):
  comment = TextAreaField('.')
  submit = SubmitField('Submit')
  

app/__init__.py
from flask import Flask
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_bootstrap import Bootstrap

db = SQLAlchemy()
bootstrap = Bootstrap()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login' 
mail = Mail()

def create_app(config_name):
  app = Flask(__name__)

  app.config.from_object(config_options[config_name])

  db.init_app(app)
  login_manager.init_app(app)
  bootstrap.init_app(app)
  mail.init_app(app)

  from .main import main as main_blueprint
  app.register_blueprint(main_blueprint)

  from .auth import auth as auth_blueprint
  app.register_blueprint(auth_blueprint, url_prefix= '/authenticate')


  return app
  

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import error, views

app/main/views.py
from flask import render_template, url_for, redirect, abort, request
from . import main
from .. import db
from ..models import Blog, User, Comment, Subscribe
from .forms import CommentForm, BlogPostForm 
from flask_login import login_required, current_user
from ..request import get_quotes
from ..email import mail_message
import time


@main.route('/')
def index():
  blog = Blog.get_blogs_content()
  title = 'Blog'
  blog.reverse()
  quote = get_quotes() 
  return render_template('index.html', blogs=blog, title=title, quote=quote)

@main.route('/post/blog', methods=['GET', 'POST',])
@login_required
def postblog():
  blogform = BlogPostForm()

  if blogform.validate_on_submit():
    title = blogform.title.data
    content = blogform.content.data
    
    newblog = Blog(title=title, content=content, user_id=current_user.id)
    newblog.save_blog()

    for i in Subscribe.query.all():
      mail_message("New Blog Is Out", "email/update_subscriber", i.email, newblog=newblog)

    return redirect(url_for('main.profile', uname=current_user.username))

  quote = get_quotes()
  return render_template('profile/postblog.html', blogform=blogform, quote=quote)

@main.route('/user/<uname>')
@login_required
def profile(uname):
  user = User.query.filter_by(username = uname).first()

  
  if user is None:
    abort(404)
  else:
    blog = Blog.query.filter_by(user_id=current_user.id).all()
    quote = get_quotes()
    return render_template('profile/profile.html', user = user, blog = blog, quote=quote)

@main.route('/comment/<id>', methods=['GET', 'POST'])
@login_required
def comment(id):
  form = CommentForm()
  blog = Blog.query.filter_by(id=id).first()

  if form.validate_on_submit():
    comment = form.comment.data
    new_comment = Comment(comment = comment, user_id = current_user.id, blog_id = id)

    new_comment.save_comment()
    return redirect(url_for('main.index'))
  
  blogcomment = Comment.query.filter_by(blog_id=id).all()
  quote = get_quotes()

  return render_template('profile/comment.html', comment=form, blog=blog, blogcomment = blogcomment, quote=quote)

@main.route('/post/<id>/comments', methods=['GET'])
def viewcomments(id):
  allcomments = Comment.query.filter_by(blog_id=id).all()
  quote = get_quotes()
  return render_template('profile/viewcomment.html', allcomments=allcomments, quote=quote)

@main.route('/post/<id>/delete', methods = ['GET', 'POST'])
def deletePost(id):
  todele = Blog.query.filter_by(id=id).first()
  db.session.delete(todele)
  db.session.commit()
  return redirect(url_for('main.profile', uname=current_user.username))

@main.route('/post/<id>/comment/delete', methods = ['GET', 'POST'])
def deleteComment(id):
  todele = Comment.query.filter_by(id=id).first()
  db.session.delete(todele)
  db.session.commit()
  return redirect(url_for('main.profile', uname=current_user.username))

@main.route('/post/<id>', methods=['POST', 'GET'])
def fullblog(id):
  blogdetail = Blog.query.filter_by(id=id).first()
  quote = get_quotes()
  return render_template('fullblog.html', blogdetail=blogdetail,   quote = quote)

@main.route('/subscribe', methods=['POST'])
def subscribe():
        email = request.form.get('subscriber')
        new_sub = Subscribe(email=email)
        new_sub.save_subscriber()
        mail_message("Subscribed to Maingi Blog","email/welcome_subscriber", email)

        return redirect(url_for('main.index'))
 

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
  <script src="{{ url_for('static', filename='js/script.js') }}"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  <title>Personal Blog</title>
</head>
<body>
  {% block navbar %}
    {% include 'navbar.html' %}
  {% endblock %}
  <div class="container d-md-flex justify-content-center align-items-center">
    <div class="blogcont">
  {% block content %}


  {% endblock %}
</div>
</div>
  {% block footer %}
    {% include 'footer.html' %}
  {% endblock %}
</body>
</html>

app/templates/fullblog.html
{% extends 'base.html' %}

{% block content %}
<h5 class="text-center mb-3">Blog | Post</h5>
<a href="/">Go Back</a>
<div class="d-md-flex justify-content-between align-content-center">
<h2 >{{ blogdetail.title| capitalize }}</h2>
<p>Author: {{ blogdetail.users }}</p>
<span>Comments {{blogdetail.comments.count()}}</span>
</div>

<hr>
<p>{{ blogdetail.content }}</p>
<a href="{{ url_for('main.comment', id= blogdetail.id) }}"><button class="btn btn-outline-success">Comment</button></a>

<hr class="mt-3 mb-3">

<div class="text-center">
  <p>{{ quote.quote }}</p>
  <sub>--{{ quote.author }}--</sub>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content%}
<h5 class="text-center mb-3">Blog | Home</h5>


    {% for blog in blogs %}
    <div class="indexblog p-3">
      <div class="d-md-flex justify-content-between align-items-center p-1">
        <h3>{{ blog.title|capitalize }}</h3>
        <span>Posted on {{ blog.dateposted.strftime('%a %b %d, %Y')}}</span>
      </div>
      <p>{{ blog.content|truncate(200) }}</p>
      <div class="d-md-flex justify-content-between align-items-center">
        <span>Author: {{ blog.users}}</span>
        <a class="fullblog" href="{{ url_for('main.fullblog', id= blog.id) }}">View Full Blog</a>
        <a href="{{ url_for('main.comment', id= blog.id) }}"><button class="btn btn-outline-success">Comments <span>{{blog.comments.count()}}</span></button></a>
      </div>

    </div>

    <hr>

    {% endfor %}
    <div class="text-center">
      <p>{{ quote.quote }}</p>
      <sub>--{{ quote.author }}--</sub>
    </div>



{% endblock %}

app/templates/navbar.html
<div class="navbar navcustom" role="navigation">
  <div class="container-fluid">
      <div class="navbar-header">
          <a href='/' class="nav-item nav-link title ml-md-3">Maingi <span>Blog</span></a>
      </div>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <form class="d-md-flex justify-content-center align-items-center" action="{{url_for('main.subscribe')}}" method="POST">
        <input type="email"  class="form-control " name ="subscriber" required placeholder="Email Address...">
        <button class="btn btn-md btn-outline-info ml-2" id="subs">Subscribe</button>
      </form>


      <div class="nav navbar-nav navbar">
        <ul class="nav d-flex">
          <li><a class="nav-item other" href="/">Home</a></li>
          <li><a class="nav-item other" href="{{ url_for('main.postblog') }}">Post A Blog</a></li>
          {% if current_user.is_authenticated %}
          <li><a class="nav-item other" href="{{ url_for('main.profile', uname = current_user.username) }}">{{ current_user.username| capitalize }}</a></li>
          <li><a class="nav-item other" href="{{url_for('auth.logout')}}">Log Out</a></li>
          {% else %}
          <li><a class="nav-item other" href="{{url_for('auth.login')}}">Sign In</a></li>
          {% endif %}
        </ul>

      </div>
  </div>
</div>
<hr>

app/templates/profile/comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<a href="/">Back</a>
<div>
    <div class="d-md-flex justify-content-between align-items-center p-2">
      <h3>{{ blog.title|capitalize }}</h3>
      <span>Posted on {{ blog.dateposted.strftime('%a %b %d, %Y')}}</span>
    </div>
    <p>{{ blog.content }}</p>
    <div class="d-md-flex justify-content-between align-items-center">
      <span>Author -- {{ blog.users}} --</span>
    </div>

  </div>



{{wtf.quick_form(comment)}}
<h4>Comments For {{ blog.title }}</h4>
<div class="row">

{% if blogcomment %}
{% for justone in blogcomment%}
<div class="blogcomment col-md-3">
    <p>{{ justone.comment }}</p>
    <p>Comment By <span class="text-success">{{ justone.users| capitalize}}</span></p>
</div>
{% endfor %}
{% else %}
<p>No comments Yet</p>
{% endif %}
</div>

<div class="text-center">
    <p>{{ quote.quote }}</p>
    <sub>--{{ quote.author }}--</sub>
</div>



{% endblock %}

app/templates/profile/postblog.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<h5 class="text-center mb-3">Blog | Blog_Post</h5>

<a href="{{ url_for('main.profile', uname=current_user.username)}}">Back</a>
<div class="container d-flex justify-content-center align-items-center mt-5">
  <div class="postForm">
    <h3 class="text-center mb-4">Post A Blog</h3>
    {{ wtf.quick_form(blogform)}}
  </div>
</div>
<p class="text-danger">Give it a minute will take you back Profile</p>
<hr>
<div class="text-center mt-md-4">
  <p>{{ quote.quote }}</p>
  <sub>--{{ quote.author }}--</sub>
</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<h5 class="text-center mb-3">Blog | Profile</h5>

<div class="row">
  <h1 class='text-center mb-5'>Profile</h1>
  <div class="col-md-4">
    <div class="defaultimg">
      <i class="fa fa-user-circle" aria-hidden="true"></i>
    </div>
    <hr>
    <h3> {{user.fname| capitalize}} {{user.sname| capitalize}}</h3>
    <p>@{{user.username}}</p>
    <p>Role: Author</p>

    <a href="{{ url_for('main.postblog') }}"><button class="btn btn-outline-dark">Post A Blog</button></a>
  </div>
  <div class="col-md-8">
    {% if blog %}
    {% for justone in blog%}
    <div class="blogpro mt-4">
      <div class="d-md-flex justify-content-between">
        <h3>{{ justone.title|capitalize }}</h3>
        <p>Posted: {{ justone.dateposted.strftime('%a %b %d, %Y') }}</p>
      </div>
      <div class="text">
        <p>{{ justone.content|truncate(100)}}</p>
      </div>
      <div class="d-md-flex justify-content-around align-items-center">
        <span><i class="fa fa-comments" aria-hidden="true"></i> {{justone.comments.count()}}</span>
        <a href="{{ url_for('main.viewcomments', id=justone.id) }}">View Comments</a>
        <a class="text-danger" href="{{ url_for('main.deletePost', id=justone.id) }}"><i class="fa fa-trash-o" aria-hidden="true"></i>
        </a>
      </div>
    </div>
    {% endfor %}
    {% else %}
      <p>No Blogs Yet</p>
    {% endif %}
  </div>
  <hr class='mt-4'>
  <div class="text-center">
      <p>{{ quote.quote }}</p>
      <sub>--{{ quote.author }}--</sub>
    </div>
</div>
{% endblock %}

app/templates/profile/viewcomment.html
{% extends 'base.html' %}

{% block content %}
<a href="{{ url_for('main.profile', uname=current_user.username)}}">Back</a>

<h1>View Comments </h1>


{% for justone in allcomments %}
<div class="p-3">
  <p>{{ justone.comment }}</p>
  <a class="text-danger" href="{{ url_for('main.deleteComment', id=justone.id) }}">Delete</a>
  <hr>
</div>

{% endfor %}

<div class="text-center">
  <p>{{ quote.quote }}</p>
  <sub>--{{ quote.author }}--</sub>
</div>
{% endblock %}